# Netlify configuration file for a React app

[build]
  # Set the build command for your React app
  command = "CI= npm run build"

  # Set the directory that contains the built files
  publish = "build"

  # Set the base directory for your site (you can adjust this as needed)
  base = "/"

# Define redirects for client-side routing
[[redirects]]
  # Redirect all requests to the root "index.html" for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Define environment variables if needed
[context.production]
  NODE_ENV = "production"

# Additional build settings or headers if required
